#!/bin/bash
# Setup script for installing Git hooks and Pylint configuration
# Run this script once to set up the pre-commit hook

set -e

echo "╔════════════════════════════════════════════════════════╗"
echo "║   Git Pre-Commit Hook Setup for Pylint                ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check if in a git repository
if [ ! -d .git ]; then
    echo -e "${RED}❌ Error: Not a git repository${NC}"
    echo "Please run this script from the root of your git repository."
    exit 1
fi

echo "Current directory: $(pwd)"
echo ""

# Step 1: Check/Install Pylint
echo "Step 1: Checking Pylint installation..."
if command -v pylint &> /dev/null; then
    PYLINT_VERSION=$(pylint --version | head -1)
    echo -e "${GREEN}✓ Pylint is installed: $PYLINT_VERSION${NC}"
else
    echo -e "${YELLOW}⚠ Pylint not found. Installing...${NC}"
    
    # Try to install with pip
    if command -v pip3 &> /dev/null; then
        pip3 install pylint
        echo -e "${GREEN}✓ Pylint installed successfully${NC}"
    elif command -v pip &> /dev/null; then
        pip install pylint
        echo -e "${GREEN}✓ Pylint installed successfully${NC}"
    else
        echo -e "${RED}❌ Error: pip not found${NC}"
        echo "Please install pip and run this script again."
        exit 1
    fi
fi
echo ""

# Step 2: Update requirements.txt
echo "Step 2: Updating requirements.txt..."
if ! grep -q "^pylint" requirements.txt 2>/dev/null; then
    echo "pylint==3.0.3" >> requirements.txt
    echo -e "${GREEN}✓ Added pylint to requirements.txt${NC}"
else
    echo -e "${BLUE}ℹ Pylint already in requirements.txt${NC}"
fi
echo ""

# Step 3: Create .pylintrc configuration file
echo "Step 3: Creating .pylintrc configuration..."
cat > .pylintrc << 'EOF'
[MASTER]
# Use multiple processes to speed up Pylint
jobs=4

# Pickle collected data for later comparisons
persistent=yes

# List of plugins (as comma separated values)
load-plugins=

# Discover python modules and packages in the file system subtree
recursive=yes

[MESSAGES CONTROL]
# Disable specific messages that are too strict for this project
disable=
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring,
    too-few-public-methods,
    too-many-arguments,
    too-many-instance-attributes,
    too-many-locals,
    too-many-branches,
    too-many-statements,
    invalid-name,
    line-too-long,
    fixme,
    duplicate-code

[REPORTS]
# Set the output format
output-format=text

# Tells whether to display a full report or only the messages
reports=no

# Activate the evaluation score
score=yes

[FORMAT]
# Maximum number of characters on a single line
max-line-length=100

# Maximum number of lines in a module
max-module-lines=1000

# String used as indentation unit
indent-string='    '

[BASIC]
# Good variable names which should always be accepted
good-names=i,j,k,ex,Run,_,id,db,app

# Regular expression matching correct argument names
argument-rgx=[a-z_][a-z0-9_]{0,30}$

# Regular expression matching correct variable names
variable-rgx=[a-z_][a-z0-9_]{0,30}$

# Regular expression matching correct constant names
const-rgx=(([A-Z_][A-Z0-9_]*)|(__.*__))$

# Regular expression matching correct attribute names
attr-rgx=[a-z_][a-z0-9_]{0,30}$

[DESIGN]
# Maximum number of arguments for function / method
max-args=7

# Maximum number of attributes for a class
max-attributes=10

# Maximum number of public methods for a class
max-public-methods=20

[IMPORTS]
# Deprecated modules which should not be used
deprecated-modules=optparse,imp

[EXCEPTIONS]
# Exceptions that will emit a warning when being caught
overgeneral-exceptions=builtins.Exception
EOF

echo -e "${GREEN}✓ Created .pylintrc configuration file${NC}"
echo ""

# Step 4: Create pre-commit hook
echo "Step 4: Installing pre-commit hook..."

HOOK_FILE=".git/hooks/pre-commit"

# Backup existing hook if present
if [ -f "$HOOK_FILE" ]; then
    echo -e "${YELLOW}⚠ Existing pre-commit hook found. Creating backup...${NC}"
    cp "$HOOK_FILE" "$HOOK_FILE.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${GREEN}✓ Backup created${NC}"
fi

# Create the hook
cat > "$HOOK_FILE" << 'HOOKEOF'
#!/bin/bash
# Pre-commit hook for Pylint checking
# Auto-generated by setup script

set -e

echo "🔍 Running Pylint checks on Python files..."
echo ""

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get list of staged Python files
PYTHON_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.py$' || true)

if [ -z "$PYTHON_FILES" ]; then
    echo "ℹ️  No Python files staged for commit."
    exit 0
fi

echo "Python files to check:"
echo "$PYTHON_FILES" | sed 's/^/  • /'
echo ""

# Check if pylint is installed
if ! command -v pylint &> /dev/null; then
    echo -e "${RED}❌ Pylint is not installed!${NC}"
    echo ""
    echo "Please install it with:"
    echo "  pip install pylint"
    echo ""
    exit 1
fi

# Create temporary directory for results
TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

ERROR_FILE="$TEMP_DIR/errors.txt"
WARNING_FILE="$TEMP_DIR/warnings.txt"

# Run pylint on each file
HAS_ERRORS=0
TOTAL_FILES=0
FILES_WITH_ERRORS=0
FILES_WITH_WARNINGS=0

for file in $PYTHON_FILES; do
    if [ ! -f "$file" ]; then
        continue
    fi
    
    TOTAL_FILES=$((TOTAL_FILES + 1))
    echo -e "${BLUE}Checking: $file${NC}"
    
    # Run pylint and capture output (use .pylintrc if exists)
    if [ -f ".pylintrc" ]; then
        PYLINT_OUTPUT=$(pylint --rcfile=.pylintrc "$file" 2>&1 || true)
    else
        PYLINT_OUTPUT=$(pylint "$file" 2>&1 || true)
    fi
    
    PYLINT_EXIT_CODE=$?
    
    # Pylint exit codes:
    # 0 - No errors
    # 1 - Fatal message issued
    # 2 - Error message issued
    # 4 - Warning message issued
    # 8 - Refactor message issued
    # 16 - Convention message issued
    # 32 - Usage error
    
    # Check for errors (exit codes 1, 2, or 32)
    if [ $PYLINT_EXIT_CODE -eq 1 ] || [ $PYLINT_EXIT_CODE -eq 2 ] || [ $PYLINT_EXIT_CODE -eq 32 ]; then
        echo -e "  ${RED}✗ Errors found${NC}"
        echo "$PYLINT_OUTPUT" | grep -E "^[^:]+:[0-9]+:[0-9]+: [EF][0-9]+" >> "$ERROR_FILE" 2>/dev/null || true
        FILES_WITH_ERRORS=$((FILES_WITH_ERRORS + 1))
        HAS_ERRORS=1
    elif [ $PYLINT_EXIT_CODE -eq 0 ]; then
        echo -e "  ${GREEN}✓ No issues found${NC}"
    else
        # Only warnings, refactor, or convention messages
        echo -e "  ${YELLOW}⚠ Warnings found (non-blocking)${NC}"
        echo "$PYLINT_OUTPUT" | grep -E "^[^:]+:[0-9]+:[0-9]+: [WRC][0-9]+" >> "$WARNING_FILE" 2>/dev/null || true
        FILES_WITH_WARNINGS=$((FILES_WITH_WARNINGS + 1))
    fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Display results
if [ $HAS_ERRORS -eq 1 ]; then
    echo -e "${RED}❌ COMMIT BLOCKED: Pylint found errors!${NC}"
    echo ""
    echo "Files checked: $TOTAL_FILES"
    echo "Files with errors: $FILES_WITH_ERRORS"
    echo "Files with warnings: $FILES_WITH_WARNINGS"
    echo ""
    
    if [ -f "$ERROR_FILE" ] && [ -s "$ERROR_FILE" ]; then
        echo -e "${RED}Errors that must be fixed:${NC}"
        echo ""
        cat "$ERROR_FILE"
        echo ""
    fi
    
    if [ -f "$WARNING_FILE" ] && [ -s "$WARNING_FILE" ]; then
        echo -e "${YELLOW}Warnings (informational only):${NC}"
        echo ""
        head -20 "$WARNING_FILE"
        if [ $(wc -l < "$WARNING_FILE") -gt 20 ]; then
            echo "... ($(wc -l < "$WARNING_FILE") warnings total)"
        fi
        echo ""
    fi
    
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Please fix the errors above and try committing again."
    echo ""
    echo "To see full output: pylint <filename>"
    echo "To skip this check (not recommended): git commit --no-verify"
    echo ""
    exit 1
else
    echo -e "${GREEN}✅ All Pylint checks passed!${NC}"
    echo ""
    echo "Files checked: $TOTAL_FILES"
    
    if [ $FILES_WITH_WARNINGS -gt 0 ]; then
        echo "Files with warnings: $FILES_WITH_WARNINGS (non-blocking)"
        echo ""
        echo -e "${YELLOW}Note: Some warnings were found but are not blocking the commit.${NC}"
        echo "Consider reviewing them with: pylint <filename>"
    fi
    
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "✓ Proceeding with commit..."
    exit 0
fi
HOOKEOF

chmod +x "$HOOK_FILE"
echo -e "${GREEN}✓ Pre-commit hook installed and made executable${NC}"
echo ""

# Step 5: Add .pylintrc to git
echo "Step 5: Adding configuration files to git..."
if [ -f .pylintrc ] && ! git ls-files --error-unmatch .pylintrc &> /dev/null; then
    git add .pylintrc
    echo -e "${GREEN}✓ Added .pylintrc to git staging${NC}"
else
    echo -e "${BLUE}ℹ .pylintrc already tracked${NC}"
fi

if ! git ls-files --error-unmatch requirements.txt &> /dev/null; then
    git add requirements.txt
    echo -e "${GREEN}✓ Added requirements.txt to git staging${NC}"
else
    echo -e "${BLUE}ℹ requirements.txt already tracked${NC}"
fi
echo ""

# Step 6: Test the hook
echo "Step 6: Testing the pre-commit hook..."
echo ""
echo "Creating a test Python file with an intentional error..."

# Create test file
mkdir -p test_pylint
cat > test_pylint/test_error.py << 'TESTEOF'
# Test file with intentional error
import sys

def test_function():
    undefined_variable  # This will cause an error
    return True
TESTEOF

echo "Staging the test file..."
git add test_pylint/test_error.py

echo ""
echo "Running git commit (this should fail)..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if git commit -m "Test commit (should fail)" 2>&1 | tee /tmp/test_output.txt; then
    echo ""
    echo -e "${RED}❌ Test failed: Commit should have been blocked${NC}"
    git reset HEAD~1 2>/dev/null || true
else
    echo ""
    echo -e "${GREEN}✓ Test passed: Commit was correctly blocked${NC}"
fi

# Clean up test
git reset HEAD test_pylint/test_error.py 2>/dev/null || true
rm -rf test_pylint
echo ""

# Final summary
echo "╔════════════════════════════════════════════════════════╗"
echo "║              Setup Complete! ✅                        ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "What was installed:"
echo "  • Pylint (Python linter)"
echo "  • .pylintrc (configuration file)"
echo "  • Git pre-commit hook"
echo "  • Updated requirements.txt"
echo ""
echo "How it works:"
echo "  1. When you run 'git commit', the hook automatically runs"
echo "  2. Pylint checks all staged Python files"
echo "  3. Errors block the commit"
echo "  4. Warnings are shown but don't block"
echo ""
echo "Useful commands:"
echo "  • Test manually: pylint <filename>"
echo "  • Skip hook once: git commit --no-verify"
echo "  • Configure Pylint: edit .pylintrc"
echo "  • Check all Python files: find . -name '*.py' -not -path './venv/*' | xargs pylint"
echo ""
echo "Next steps:"
echo "  1. Review the .pylintrc file and adjust as needed"
echo "  2. Run: git add .pylintrc"
echo "  3. Commit the configuration: git commit -m 'Add Pylint configuration and pre-commit hook'"
echo ""
echo -e "${GREEN}Happy coding! 🚀${NC}"
